import Head from 'next/head';
import { Container } from '@interchain-ui/react';
import { Header } from './Header';
import { Footer } from './Footer';
import { Minting } from './Minting';
import { Staking } from './Staking';
import { Swap } from './Swap';
import { Projects } from './Projects';
import { Faq } from './Faq';
import { useState } from 'react';
import { CHAIN_NAME, CHAIN_NAME_STORAGE_KEY } from "@/config";

export function Layout({ children }: { children: React.ReactNode }) {
  const [currentSection, setCurrentSection] = useState('minting');
  const [chainName, setChainName] = useState(CHAIN_NAME);

  const renderSection = () => {
    switch (currentSection) {
      case 'minting':
        return <Minting />;
      case 'staking':
        return <Staking />;
      // Add other cases for different sections
      case 'swapping':
        return <Swap />;
      case 'projects':
        return <Projects />;
      case 'faq':
        return <Faq />;
      default:
        return <Minting />;
    }
  };

  function handleChainChange(chainName?: string) {
    if (chainName) {
      setChainName(chainName);
      localStorage.setItem(CHAIN_NAME_STORAGE_KEY, chainName!);
    }
  }

  return (
    <Container maxWidth="80rem" attributes={{ py: '$14' }}>
      <Head>
        <title>Solar DAO</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setCurrentSection={setCurrentSection} />
      {renderSection()}
      <Footer chainName={chainName} handleChainChange={handleChainChange} />
    </Container>
  );
}
